### ISSUE TITLE
frontend improvement, last

### ISSUE THREAD

**Issue by thanhduc2000** [dinhnhobao/NUSBuy#10]
1. product_list.html
ông xem đoạn code trong file:
{% if user %}
    <...>Welcome, {{ user.username }} {{ user.name }}</...>
    {% for account in user.socialaccount_set.all %}
        <..> You logged in via {{ account.provider }}. </..>
        {% if account.get_avatar_url %}
          <p><img width="50" height="50" src="..." /></p>
        {% endif %}

        {% if account.extra_data.username %}
          <p>Username: {{ account.extra_data.username }}</p>
        {% endif %}
    {% endfor %}
{% endif %}

cái dòng   You logged in via {{ account.provider }}.  thì ông thêm khung nền trắng xung quanh (thành một cái text box có màu ấy)

còn Welcome, {{ user.username }} {{ user.name }} (tên)
và {{ account.get_avatar_url }} (avatar) thì ông chỉnh thành như này:

![image](https://user-images.githubusercontent.com/42399230/61713055-e5d77580-ad81-11e9-9444-6a00093ba5cc.png)
![image](https://user-images.githubusercontent.com/42399230/61713064-e96afc80-ad81-11e9-9ca1-e0bac4a2338a.png) (giống như facebook, chữ Bảo thì để fullname luôn)
ông làm nút hyperlink cho   nút 'here' chỗ see information you provided luôn nhé

chú ý
- chỗ name thì để  {{ user.username }} {{ user.name }} nhé, lí do: tùy vào trang login (github/facebook/google), mà cái attribute tên nó sẽ lưu là username hoặc name, nên phải ghi cả 2 cái;

- {{ account.get_avatar_url }} phải access trong vòng loop (account khác user)
làm nút kiểu vậy này:
![image](https://user-images.githubusercontent.com/42399230/61713393-a65d5900-ad82-11e9-94fa-9808286decdf.png), để ở chỗ navbar (login/logout)

2. product_list.html
mấy dòng chữ
There are currently 0 listings on NUSBuy.
There are 0 items as per requested.
There are no product listings yet. (trong trường hợp 0 có)

thì ông để text box wrap quanh luôn giống cái  You logged in via {{ account.provider }}. ở trên

3. giới hạn bề ngang (của product_list.html, và mấy cái khác luôn?)
hiện tại
![image](https://user-images.githubusercontent.com/42399230/61713505-f63c2000-ad82-11e9-8dcb-4e54b3e023a0.png)
![image](https://user-images.githubusercontent.com/42399230/61713585-25eb2800-ad83-11e9-834e-01eb5a24780e.png)

bề phải của page chỉ tới hết product ngoài cùng thôi, website còn dư chỗ nhiều quá

4. Sửa nút Search + Create a listing màu mè hơn (không giống kiểu của navbar)
5.
![image](https://user-images.githubusercontent.com/42399230/61714076-2fc15b00-ad84-11e9-95d6-b5dd12822811.png)

6. để background của CẢ website nền trắng nhạt đi (giống Github này), nền trắng nhạt còn khung text box thì trắng đậm (như GitHub/Carousell)

7. 
![image](https://user-images.githubusercontent.com/42399230/61714497-30a6bc80-ad85-11e9-85ab-d7684452f9fa.png)
làm nút share facebook và twitter to hơn (to ngang mấy cái nút kia) luôn

8. product_detail.html
ông log in bằng github rồi tạo item để xem hoặc vô http://127.0.0.1:8000/post/4/

ông vô code html:     <div class="item9"> thì sẽ thấy có rất nhiều attribute để trình bày (có mấy cái trùng nhau như name/username, vì tùy platform retrieve name sẽ khác nhau. nhưng
có các attribute quan trọng (giống phần 1.) là username/name, avatar_url

thì ông làm một khung trắng như thế này:
![image](https://user-images.githubusercontent.com/42399230/61715202-c68f1700-ad86-11e9-8828-5f9fd268e3d6.png)

hình thì là avatar_url, tên thì name/username, còn chỗ joined/verified thì ông thay bằng một đống code t đã ghi sẵn trong file nhé
https://sg.carousell.com/p/%F0%9F%9A%9A-gre-prep-plus-2019-kaplan-230271632/?ref=profile&ref_referrer=%2Fmadhura_20%2F%3Ft-source%3Dsearch_results%26t-source_query%3Dproducts&ref_sId=6574076&ref_t-source=search_results&ref_t-source_query=products
ô vô đây để xem vị trí của ô author này so với các ô khác trong cùng web

9 (nếu làm dc). product_create.html nếu sửa cái form lại đẹp/màu mè thì càng tốt
10. sửa nút Yes/No màu mè hơn trng product_delete.html (chú ý mình chỉ delete đc cái nào mình tao thôi nhé, nếu k nó sẽ tự redirect về trang chủ)

11. rà soát lại tất cả các file html trong products, nếu ô thấy file nào làm màu mè thêm dc thì làm (nhưng chắc nãy giờ là hết rồi, nhớ nhắc t update product_detail_guest với product_category nhé)

**Comment by dinhnhobao** [comment]
12. (cái này bị từ lúc cũ nhưng t chưa fix đc)
lỗi:
nếu ô chọn sort 1 trong các thứ xong, rồi chọn sort lần nữa; thì sort nó sẽ bị chồng lên nhau. Tương tự cho cái See items.
ông xem trong html code, nếu ông bỏ {{params}} đi thì nó sẽ không kết hợp dc nhiều cái với nhau (ví dụ vừa search vừa sort, vừa search vừa filter, etc.), nên h tìm cách fix sao để dc.

ông nhìn cái url ấy, fix sao kiểu thấy cái sort thứ hai thì bỏ cái đầu tiên hay sao đó

**Comment by thanhduc2000** [comment]
1
2
3 tạo lại mới thì dc, ok(chinh cai guest la dc, là sao, sao lúc đc lúc không? à r hiểu
để làm xong t paste qua luôn
4
5
6 (trong issue t ghi thiếu), ông làm viền xám/nhạt xung quanh khung trắng dc k (như github này)
xung quanh cái khung ô item cho viền vậy luôn/khung trong product_list.html (nchg tất cả text box làm v)
7 chưa fix
8 để hình avatar + username to lên (size chữ to bằng chữ tên title của item ấy), hình thì dựa vào đó scale to lên
9
10
11 sửa chỗ same category (làm button đi)
12 unsolved

k ghi là coi như ok nhé.

**Comment by thanhduc2000** [comment]
3ok 
6 khung There are currently 3 listings on NUSBuy. ô làm mỏng đi (giống mấy cái a ok v dc r
7 ok
8 ok 11 ok 
12 unsolved
ô fix xong lần này r commit nhé
